@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ManageMeParser" as ManageMeParser LOGIC_COLOR
participant ":AddModuleCommandParser" as AddModuleCommandParser LOGIC_COLOR
participant "a:AddModuleCommand" as AddModuleCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("addMod n/name")
activate LogicManager

LogicManager -> ManageMeParser : parseCommand("addMod n/name")
activate ManageMeParser

create AddModuleCommandParser
ManageMeParser -> AddModuleCommandParser
activate AddModuleCommandParser

AddModuleCommandParser --> ManageMeParser
deactivate AddModuleCommandParser

ManageMeParser -> AddModuleCommandParser : parse("n/name")
activate AddModuleCommandParser

create AddModuleCommand
AddModuleCommandParser -> AddModuleCommand
activate AddModuleCommand

AddModuleCommand --> AddModuleCommandParser : a
deactivate AddModuleCommand

AddModuleCommandParser --> ManageMeParser : a
deactivate AddModuleCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddModuleCommandParser -[hidden]-> ManageMeParser
destroy AddModuleCommandParser

ManageMeParser --> LogicManager : a
deactivate ManageMeParser

LogicManager -> AddModuleCommand : execute(model)
activate AddModuleCommand

AddModuleCommand -> Model : addModule(module)
activate Model

Model --> AddModuleCommand
deactivate Model

create CommandResult
AddModuleCommand -> CommandResult
activate CommandResult

CommandResult --> AddModuleCommand
deactivate CommandResult

AddModuleCommand --> LogicManager : result
deactivate AddModuleCommand

[<--LogicManager
deactivate LogicManager
@enduml
