@startuml
(*) -> User enters archive Command
--> "Gets current DateTime"
--> "Copies current data file into a timestamped 'archive.json' file"
if "" then
-right>[archive file creation succeeded] "Prints Success message to user"
-down-> (*)
else
-left> [archive file creation failed] "Throws CommmandException"
endif
-down-> (*)
@enduml
