@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ManageMeParser" as ManageMeParser LOGIC_COLOR
participant ":MarkTaskCommandParser" as MarkTaskCommandParser LOGIC_COLOR
participant "d:MarkTaskCommand" as MarkTaskCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("markTask 2")
activate LogicManager

LogicManager -> ManageMeParser : parseCommand("markTask 2")
activate ManageMeParser

create MarkTaskCommandParser
ManageMeParser -> MarkTaskCommandParser
activate MarkTaskCommandParser

MarkTaskCommandParser --> ManageMeParser
deactivate MarkTaskCommandParser

ManageMeParser -> MarkTaskCommandParser : parse("2")
activate MarkTaskCommandParser

create MarkTaskCommand
MarkTaskCommandParser -> MarkTaskCommand
activate MarkTaskCommand

MarkTaskCommand --> MarkTaskCommandParser : d
deactivate MarkTaskCommand

MarkTaskCommandParser --> ManageMeParser : d
deactivate MarkTaskCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
MarkTaskCommandParser -[hidden]-> ManageMeParser
destroy MarkTaskCommandParser

ManageMeParser --> LogicManager : d
deactivate ManageMeParser

LogicManager -> MarkTaskCommand : execute()
activate MarkTaskCommand

MarkTaskCommand -> Model : markTask(2)
activate Model

Model --> MarkTaskCommand
deactivate Model

create CommandResult
MarkTaskCommand -> CommandResult
activate CommandResult

CommandResult -->  MarkTaskCommand
deactivate CommandResult

MarkTaskCommand --> LogicManager : result
deactivate MarkTaskCommand

[<--LogicManager
deactivate LogicManager
@enduml
