@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MmMainWindow
Class HelpWindow
Class ResultDisplay
Class XYZListPanel
Class XYZCard
Class ModuleWindow
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MmMainWindow
MmMainWindow --> "1" HelpWindow
MmMainWindow *-down-> "1" CommandBox
MmMainWindow *-down-> "1" ResultDisplay
MmMainWindow *-down-> "1" XYZListPanel
MmMainWindow *-down-> "1" ModuleWindow

XYZListPanel -down-> "*" XYZCard

MmMainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
XYZListPanel --|> UiPart
XYZCard --|> UiPart
ModuleWindow --|> UiPart
HelpWindow -down-|> UiPart

XYZCard ..> Model
UiManager -right-> Logic
MmMainWindow -left-> Logic

XYZListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- ModuleWindow

note right of XYZListPanel: XYZListPanel = TaskListPanel, \nLinkListPanel, etc

MmMainWindow -[hidden]-|> UiPart
@enduml
