@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<interface>>
Class UiManager
Class MmMainWindow
Class HelpWindow
Class ModuleWindow
Class ResultDisplay
Class CommandBox
Class CalendarPanel
Class ModuleListPanel
Class TaskListPanel
Class ModuleCard
Class TaskCard
Class DayCard
Class "{abstract}\nUiPart" as UiPart
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .up.|> Ui
UiManager -down-> "1" MmMainWindow
MmMainWindow *-down->  "1" CommandBox
MmMainWindow *-down-> "1" ResultDisplay
MmMainWindow *-down-> "1" TaskListPanel
MmMainWindow *-down-> "1" ModuleListPanel
MmMainWindow *-down-> "1" CalendarPanel
MmMainWindow --> "0..1" HelpWindow
MmMainWindow --> "0..1" ModuleWindow
CalendarPanel -down-> "28..31" DayCard
ModuleListPanel -down--> "*" ModuleCard
TaskListPanel -down---> "*" TaskCard

ResultDisplay --|> UiPart
CommandBox --|> UiPart
ModuleListPanel --|> UiPart
ModuleCard --|> UiPart
TaskListPanel --|> UiPart
TaskCard --|> UiPart
HelpWindow --|> UiPart
ModuleWindow --|> UiPart
CalendarPanel --|> UiPart
MmMainWindow --|> UiPart

ModuleCard ..> Model
TaskCard ..> Model
UiManager -right-> Logic
MmMainWindow -left-> Logic

Class HiddenInside #FFFFFF
HiddenInside -[hidden]right- ResultDisplay

HelpWindow -[hidden]right- ModuleWindow
ModuleWindow -[hidden]right- ResultDisplay
ModuleListPanel -[hidden]right- TaskListPanel
CommandBox -[hidden]right- CalendarPanel
CalendarPanel -[hidden]right- ModuleListPanel
ResultDisplay -[hidden]right- CommandBox
@enduml
